export enum ActionTypes {
  SET_MAILINGS,
  SET_MAILING_RECEIVERS,
  SELECT_MAILING,
  ADD_MAILING,
  DELETE_MAILING,
  UPDATE_MAILING,
  SEND_TEST_EMAIL,
  // UI actions
  SHOW_ADD_FORM,
  HIDE_ADD_FORM,
  SHOW_ERROR
}
